name: Check Secrets

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Access secrets and check if null
        env:
          NAME: ${{ secrets.MY_NAME }}
          RUNNER_IP: ${{ secrets.MY_IP }}
          EXTRA_VAR: ${{ secrets.EXTRA_VAR }}
        run: |
          if [ -n "$NAME" ]; then
            echo "NAME is not null: $NAME"
          else
            echo "NAME is null or empty"
          fi

          if [ -n "$RUNNER_IP" ]; then
            echo "RUNNER_IP is not null: $RUNNER_IP"
          else
            echo "RUNNER_IP is null or empty"
          fi

          if [ -n "$EXTRA_VAR" ]; then
            echo "EXTRA_VAR is not null: $EXTRA_VAR"
          else
            echo "EXTRA_VAR is null or empty"
          fi
